name: Clang

on: push

jobs:
  clang:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 11
            os: ubuntu-22.04
          - version: 14
            os: ubuntu-24.04
          - version: 18
            os: ubuntu-24.04
          - version: 19
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch clang-${{ matrix.version }} cmake git libarchive-dev libcurl4-gnutls-dev libunshield-dev libzip-dev pkg-config
      - name: Build with Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build with Clang ${{ matrix.version }}, statically linking standard libraries
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build_static_std_libs
          cd build_static_std_libs
          cmake ../ -DENABLE_LTO=ON -DENABLE_STATIC_STANDARD_LIBRARIES=ON
          make -j4
        if: matrix.version == 11 || matrix.version == 18
      - name: Tests of build with statically linked standard libraries
        run: |
          cd "$GITHUB_WORKSPACE"/build_static_std_libs
          ctest -V
        if: matrix.version == 11 || matrix.version == 18
