name: GCC

on: push

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 11
            os: ubuntu-22.04
          - version: 13
            os: ubuntu-24.04
          - version: 14
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch g++-${{ matrix.version }} cmake git libarchive-dev libcurl4-gnutls-dev libunshield-dev libzip-dev pkg-config
      - name: Build with GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
